build.number=4.0.0
title=Simian Similarity Analyzer
copyright=Copyright (c) 2023 Quandary Peak Research. All rights reserved.
license=Subject to the Quandary Peak Academic Software License.
web.title=${title} | Similar Code Detector
